version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-functions-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-upsbi8m332v7"
s3_prefix = "step-functions-poc"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
